sprint3 completed
ClevertecFrontendLab/d4nzS pull request #1
Opened 2023-02-16 15:52 UTC by d4nzS

2023-02-16 15:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676562946/main-loading.png)

2023-02-16 18:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676570512/main-loading.png)

2023-02-16 18:19 UTC, vvikota requested changes

2023-02-16 18:19 UTC, vvikota commented on .editorconfig
> +root = true
![image](https://user-images.githubusercontent.com/30027067/219450256-bb25ee74-1329-4518-8774-74b45453b043.png)
тут нужно открытое меню

2023-02-16 18:19 UTC, vvikota commented on .editorconfig
> +[*]
![image](https://user-images.githubusercontent.com/30027067/219450384-e911a394-7f4e-419e-a833-b8dc51bd7f43.png)
не хватает хлебных крошек

2023-02-16 18:19 UTC, vvikota commented on .editorconfig
> +insert_final_newline = true
![image](https://user-images.githubusercontent.com/30027067/219450772-7ff87578-f325-46ac-a0f9-ab8fc0a9ddc0.png)
если книга успешно загружена , то тут указывается текущая категория

2023-02-16 18:19 UTC, vvikota commented on src/components/BookContentContainer/BookContent/BookContent.tsx
> +                <svg className={classes.nav__icon} viewBox="0 0 16 16" fill="none"
svg обычно выносятся в отдельный файл и импортируется, делается это для читабельности

2023-02-16 18:19 UTC, vvikota commented on .editorconfig
> +trim_trailing_whitespace = true
по всему проекту используешь svg это хорошо, но вставляются они прям в код это не очень, по хорошему вынести бы их в отдельный файл и импортировать оттуда, это для читабельности кода. Если будешь делать и не найдешь как импортать то пиши, подскажу.

2023-02-16 18:41 UTC, d4nzS commented on .editorconfig
> +insert_final_newline = true
Немного не понял про категорию. В данном случае категория: "Все книги". Или нужно категорию самой книги здесь указывать? Просто у книги может быть не одна категория, а несколько.
Ещё очень хотел бы попросить, если есть возможность, просмотреть код. Я много чего переделал, как мне кажется, очень качественно (хочу узнать, что всё-таки можно сделать лучше). Раньше делал всё на скорую руку, потому что не хватало времени - только сейчас смог сделать лучшую версию.

2023-02-17 06:25 UTC, vvikota commented on .editorconfig
> +insert_final_newline = true
нужно показать категорию самой книги, если их несколько (категорий) то показывайте первую из массива

2023-02-17 06:27 UTC, vvikota commented on .editorconfig
> +insert_final_newline = true
код на самом деле написан довольно хорошо, единственное что бросается в глаза это свг вставленные прям в код, вот в этом месте можно сделать лучше

2023-02-17 10:17 UTC, d4nzS commented on .editorconfig
> +insert_final_newline = true
Хорошо, вынесу в отдельные файлы. Спасибо большое!

2023-02-17 15:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/d4nzS/1676646920/main-loading.png)

2023-02-17 15:26 UTC, vvikota approved these changes

2023-02-17 15:30 UTC, merged